# Generated by Django 3.2.18 on 2023-04-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camrequest',
            name='ip',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='camrequest',
            name='length',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='camrequest',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
