# Generated by Django 3.2.18 on 2023-04-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_camrequest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camrequest',
            name='time',
            field=models.BigIntegerField(default=1681356870325),
        ),
    ]
