# Generated by Django 3.2.18 on 2023-04-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20230414_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmreport',
            name='time',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='camrequest',
            name='time',
            field=models.BigIntegerField(default=1681525080291),
        ),
    ]
