# Generated by Django 3.2.18 on 2023-04-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20230414_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camrequest',
            name='time',
            field=models.BigIntegerField(default=1681525301520),
        ),
    ]
