# Generated by Django 3.2.18 on 2023-04-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_camrequest_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=8)),
                ('time', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='camrequest',
            name='time',
            field=models.BigIntegerField(default=1682213124216),
        ),
    ]
