# Generated by Django 4.2.7 on 2024-10-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('camera', models.CharField(max_length=64)),
                ('length', models.SmallIntegerField(null=True)),
                ('time', models.BigIntegerField(default=1729113581088)),
                ('ip', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
