# Generated by Django 3.2.18 on 2023-04-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20230414_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmreport',
            name='time',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='camrequest',
            name='time',
            field=models.BigIntegerField(default=1681525219728),
        ),
    ]
